/* Starter data for the BuildCycle prototype. */
const ASSET = "assets/";
const STORAGE_KEY = "buildcycle-demo-v2";
const STATE_VERSION = 3;
const listingAvailableQuantity = (listing) => {
  const explicit = Number(listing?.availableQty);
  const parsed = Number.parseFloat(String(listing?.qty || "").replace(/,/g, ""));
  const quantity = Number.isFinite(explicit) && explicit > 0 ? explicit : parsed;
  return Math.max(1, Math.floor(Number.isFinite(quantity) ? quantity : 1));
};
const defaultListings = [
  {
    id: "tiles",
    title: "Ceramic Floor Tiles — Sealed Boxes",
    category: "Tiles",
    condition: "Unused surplus",
    tag: "Available",
    price: 45,
    unit: "pc",
    qty: "40 pieces",
    location: "Tubigon, Bohol",
    distance: 2,
    image: "tiles.png",
    seller: "Jessa M.",
    rating: "4.8",
    description:
      "Clean white floor tiles left from a residential build. Still boxed and ready for pickup. Suitable for kitchens and bathrooms.",
    specs: [
      ["QUANTITY", "40 pieces"],
      ["SIZE", "30 × 30 cm"],
      ["COLOR", "Ivory"],
      ["CONDITION", "Unused surplus"],
    ],
    mine: false,
  },
  {
    id: "rebar",
    title: "Surplus Steel Rebar — 10 mm",
    category: "Steel & Metal",
    condition: "Unused surplus",
    tag: "Surplus",
    price: 48,
    unit: "kg",
    qty: "120 kg",
    location: "Calape, Bohol",
    distance: 8,
    image: "rebar.png",
    seller: "Juan Dela Cruz",
    rating: "4.8",
    description:
      "Straight 10 mm reinforcing bars left over from a building project. Stored off the ground and ready for pickup.",
    specs: [
      ["QUANTITY", "120 kg"],
      ["DIAMETER", "10 mm"],
      ["GRADE", "Construction"],
      ["CONDITION", "Unused surplus"],
    ],
    mine: true,
  },
  {
    id: "cement",
    title: "Cement Bags — Unopened",
    category: "Cement & Concrete",
    condition: "New",
    tag: "New",
    price: 220,
    unit: "bag",
    qty: "15 bags",
    location: "Tubigon, Bohol",
    distance: 1,
    image: "cement.png",
    seller: "Rico P.",
    rating: "4.7",
    description:
      "Unopened bags of Portland cement, stored in a covered dry area. Available as a full set or by bag.",
    specs: [
      ["QUANTITY", "15 bags"],
      ["WEIGHT", "40 kg / bag"],
      ["STORAGE", "Covered"],
      ["CONDITION", "New"],
    ],
    mine: false,
  },
  {
    id: "lumber",
    title: "Reclaimed Hardwood Planks — Bulk Set",
    category: "Lumber",
    condition: "Reclaimed",
    tag: "Recycled",
    price: 450,
    unit: "board",
    qty: "45 planks",
    location: "Clarin, Bohol",
    distance: 11,
    image: "lumber.png",
    seller: "Marcus D.",
    rating: "4.9",
    description:
      "A set of approximately 45 reclaimed hardwood planks from a warehouse renovation. Surface cleaned and ready for another project. Great for flooring, furniture or accent walls.",
    specs: [
      ["QUANTITY", "45 planks"],
      ["LENGTH", "8–12 ft"],
      ["THICKNESS", "2 inches"],
      ["CONDITION", "Reclaimed"],
    ],
    mine: false,
  },
  {
    id: "blocks",
    title: "Concrete Hollow Blocks — Bulk Lot",
    category: "Cement & Concrete",
    condition: "Like new",
    tag: "Available",
    price: 18,
    unit: "pc",
    qty: "200 pieces",
    location: "Tubigon, Bohol",
    distance: 3,
    image: "blocks.png",
    seller: "Juan Dela Cruz",
    rating: "4.8",
    description:
      "Standard hollow blocks from a surplus site order. Pickup can be arranged in smaller batches.",
    specs: [
      ["QUANTITY", "200 pieces"],
      ["SIZE", "Standard"],
      ["PICKUP", "Flexible"],
      ["CONDITION", "Like new"],
    ],
    mine: true,
  },
  {
    id: "plywood",
    title: "Structural Plywood Sheets",
    category: "Lumber",
    condition: "Unused surplus",
    tag: "Surplus",
    price: 590,
    unit: "sheet",
    qty: "24 sheets",
    location: "Tagbilaran, Bohol",
    distance: 43,
    image: "plywood.png",
    seller: "Juan Dela Cruz",
    rating: "4.8",
    description:
      "Surplus construction plywood, neatly stored on pallets. Great for partitions, cabinets or formwork.",
    specs: [
      ["QUANTITY", "24 sheets"],
      ["SIZE", "4 × 8 ft"],
      ["THICKNESS", "12 mm"],
      ["CONDITION", "Unused surplus"],
    ],
    mine: true,
  },
  {
    id: "wire",
    title: "Electrical Wire — Leftover Roll",
    category: "Electrical",
    condition: "Unused surplus",
    tag: "Available",
    price: 24,
    unit: "meter",
    qty: "50 meters",
    location: "Calape, Bohol",
    distance: 7,
    image: "wire.png",
    seller: "Juan Dela Cruz",
    rating: "4.8",
    description:
      "Leftover insulated electrical wire. Buyer may inspect before accepting the material.",
    specs: [
      ["QUANTITY", "50 meters"],
      ["TYPE", "Insulated"],
      ["PICKUP", "Calape"],
      ["CONDITION", "Unused surplus"],
    ],
    mine: true,
  },
  {
    id: "timber",
    title: "Reclaimed Framing Timber",
    category: "Lumber",
    condition: "Reclaimed",
    tag: "Recycled",
    price: 85,
    unit: "board",
    qty: "65 boards",
    location: "Tubigon, Bohol",
    distance: 4,
    image: "lumber.png",
    seller: "Ana V.",
    rating: "4.6",
    description:
      "Reclaimed framing timber in mixed lengths. Perfect for a smaller build or furniture project.",
    specs: [
      ["QUANTITY", "65 boards"],
      ["LENGTH", "Mixed"],
      ["MATERIAL", "Hardwood"],
      ["CONDITION", "Reclaimed"],
    ],
    mine: false,
  },
];
const defaultChats = [
  {
    id: "marcus",
    name: "Marcus D.",
    listingId: "lumber",
    type: "buying",
    last: "We can arrange pickup tomorrow afternoon.",
    time: "9:20 AM",
    online: true,
    messages: [
      {
        mine: false,
        text: "Hi there! Yes, the reclaimed planks are still available. How many are you looking for?",
        time: "9:12 AM",
      },
      {
        mine: true,
        text: "I’m interested in the full bulk set. Is the price firm?",
        time: "9:15 AM",
      },
      {
        mine: false,
        text: "For the full set, I could do ₱420 per board if you can pick it up tomorrow.",
        time: "9:18 AM",
      },
      {
        mine: true,
        text: "That works. I’ll check delivery options.",
        time: "9:20 AM",
      },
    ],
  },
  {
    id: "jessa",
    name: "Jessa M.",
    listingId: "tiles",
    type: "buying",
    last: "Yes, the tiles are still available!",
    time: "Yesterday",
    online: true,
    messages: [
      {
        mine: false,
        text: "Yes, the tiles are still available!",
        time: "Yesterday",
      },
    ],
  },
  {
    id: "rico",
    name: "Rico P.",
    listingId: "cement",
    type: "buying",
    last: "You can inspect the bags before pickup.",
    time: "Wed",
    online: false,
    messages: [
      {
        mine: false,
        text: "You can inspect the bags before pickup.",
        time: "Wed",
      },
    ],
  },
  {
    id: "buyer",
    name: "Mika L.",
    listingId: "rebar",
    type: "selling",
    last: "Is 120 kg still available?",
    time: "Mon",
    online: false,
    messages: [
      { mine: false, text: "Is 120 kg still available?", time: "Mon" },
    ],
  },
];
const freshState = () => ({
  version: STATE_VERSION,
  onboarded: false,
  authed: false,
  user: {
    name: "Juan Dela Cruz",
    email: "demo@buildcycle.ph",
    location: "Tubigon, Bohol",
  },
  listings: structuredClone(defaultListings),
  chats: structuredClone(defaultChats),
  saved: [],
  deals: [],
  reviews: [],
});
